name:                cerkefs
version:             0.5.7.0
github:              "sozysozbot/cerke"
license:             BSD3
author:              "sozysozbot"
maintainer:          "sozysozbot@gmail.com"
copyright:           "2018 sozysozbot"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/sozysozbot/cerke/tree/cfs/cfs#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- transformers
- multiset

library:
  source-dirs: src

executables:
  cerkefs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cerkefs
    - mwc-random

tests:
  cerkefs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cerkefs
    - hspec
