resolver: lts-11.3
packages:
- .
build:
  haddock: true
  haddock-arguments:
    haddock-args:         
    - --odir=haddock      
  open-haddocks: false
  haddock-internal: false
  haddock-hyperlink-source: true
