module CerkeFS.InitialBoard
(initialBoard
) where
import CerkeFS.Internal.Piece2
import CerkeFS.Board2
import qualified Data.Map as M

-- | Initial configuration of the cerke board.
initialBoard :: Board1
initialBoard = M.fromList [(sqKA,Piece {color = Huok2, prof = Kua2, side = Downward}),(sqLA,Piece {color = Huok2, prof = Maun1, side = Downward}),(sqNA,Piece {color = Huok2, prof = Kaun1, side = Downward}),(sqTA,Piece {color = Huok2, prof = Uai1, side = Downward}),(sqZA,Piece {color = Kok1, prof = Io, side = Downward}),(sqXA,Piece {color = Kok1, prof = Uai1, side = Downward}),(sqCA,Piece {color = Kok1, prof = Kaun1, side = Downward}),(sqMA,Piece {color = Kok1, prof = Maun1, side = Downward}),(sqPA,Piece {color = Kok1, prof = Kua2, side = Downward}),(sqKE,Piece {color = Kok1, prof = Tuk2, side = Downward}),(sqLE,Piece {color = Kok1, prof = Gua2, side = Downward}),(sqTE,Piece {color = Kok1, prof = Dau2, side = Downward}),(sqXE,Piece {color = Huok2, prof = Dau2, side = Downward}),(sqME,Piece {color = Huok2, prof = Gua2, side = Downward}),(sqPE,Piece {color = Huok2, prof = Tuk2, side = Downward}),(sqKI,Piece {color = Huok2, prof = Kauk2, side = Downward}),(sqLI,Piece {color = Kok1, prof = Kauk2, side = Downward}),(sqNI,Piece {color = Huok2, prof = Kauk2, side = Downward}),(sqTI,Piece {color = Kok1, prof = Kauk2, side = Downward}),(sqZI,Piece {color = Kok1, prof = Nuak1, side = Downward}),(sqXI,Piece {color = Kok1, prof = Kauk2, side = Downward}),(sqCI,Piece {color = Huok2, prof = Kauk2, side = Downward}),(sqMI,Piece {color = Kok1, prof = Kauk2, side = Downward}),(sqPI,Piece {color = Huok2, prof = Kauk2, side = Downward}),(sqZO,Tam2),(sqKAI,Piece {color = Huok2, prof = Kauk2, side = Upward}),(sqLAI,Piece {color = Kok1, prof = Kauk2, side = Upward}),(sqNAI,Piece {color = Huok2, prof = Kauk2, side = Upward}),(sqTAI,Piece {color = Kok1, prof = Kauk2, side = Upward}),(sqZAI,Piece {color = Huok2, prof = Nuak1, side = Upward}),(sqXAI,Piece {color = Kok1, prof = Kauk2, side = Upward}),(sqCAI,Piece {color = Huok2, prof = Kauk2, side = Upward}),(sqMAI,Piece {color = Kok1, prof = Kauk2, side = Upward}),(sqPAI,Piece {color = Huok2, prof = Kauk2, side = Upward}),(sqKAU,Piece {color = Huok2, prof = Tuk2, side = Upward}),(sqLAU,Piece {color = Huok2, prof = Gua2, side = Upward}),(sqTAU,Piece {color = Huok2, prof = Dau2, side = Upward}),(sqXAU,Piece {color = Kok1, prof = Dau2, side = Upward}),(sqMAU,Piece {color = Kok1, prof = Gua2, side = Upward}),(sqPAU,Piece {color = Kok1, prof = Tuk2, side = Upward}),(sqKIA,Piece {color = Kok1, prof = Kua2, side = Upward}),(sqLIA,Piece {color = Kok1, prof = Maun1, side = Upward}),(sqNIA,Piece {color = Kok1, prof = Kaun1, side = Upward}),(sqTIA,Piece {color = Kok1, prof = Uai1, side = Upward}),(sqZIA,Piece {color = Huok2, prof = Io, side = Upward}),(sqXIA,Piece {color = Huok2, prof = Uai1, side = Upward}),(sqCIA,Piece {color = Huok2, prof = Kaun1, side = Upward}),(sqMIA,Piece {color = Huok2, prof = Maun1, side = Upward}),(sqPIA,Piece {color = Huok2, prof = Kua2, side = Upward})]

